### PR TITLE
fixing broken check mode in the github_key

### LINKED ISSUE #9185: Broken check mode in github_key module
### Summary

community.general.github_key fails when run in check mode (eg, when using `ansible-playbook --check ...`) 

When running without the check flag, the module works fine. 
Reviewing the code, I believe this was introduced in PR https://github.com/ansible-collections/community.general/pull/8222

Specifically, here:
https://github.com/ansible-collections/community.general/blob/3c23ce4a7bcdd08e172a58669842d4faec63d7c5/plugins/modules/github_key.py#L165

I don't have a python environment handy, but I am pretty sure this should be changed to: 

```python
'created_at': datetime.datetime.strftime(now_t, '%Y-%m-%dT%H:%M:%SZ'),
```

### Issue Type

Bug Report

### Component Name

module is github_key.py

### Ansible Version

```
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/tom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/tom/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```
Collection        Version
----------------- -------
community.general 10.0.1 

```

### Configuration

n/a

### OS / Environment

Ubuntu 24.04

### Steps to Reproduce

Given a playbook with this task: 
```yaml 
  - name: Add ssh key to github
    become: true
    community.general.github_key:
      name: "{{ key_name }}"
      token: "{{ gh_token }}"
      pubkey: "{{ pubkey }}"
      state: present
```
it works fine when running `ansible-playbook playbook.yml`
But, if it is run with check mode (ie, `ansible-playbook --check playbook.yml`) then a python exception is generated (see below for error)

### Expected Results

Expected to show that a change would occur without the error/exception

### Actual Results

```
TASK [Add ssh key to github] *******************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'datetime' has no attribute 'strftime'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/tom/.ansible/tmp/ansible-tmp-1732488395.5338001-12323-276562370367174/AnsiballZ_github_key.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/tom/.ansible/tmp/ansible-tmp-1732488395.5338001-12323-276562370367174/AnsiballZ_github_key.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/tom/.ansible/tmp/ansible-tmp-1732488395.5338001-12323-276562370367174/AnsiballZ_github_key.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.github_key', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.github_key', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_community.general.github_key_payload_k4s7yu7c/ansible_community.general.github_key_payload.zip/ansible_collections/community/general/plugins/modules/github_key.py\", line 260, in <module>\n  File \"/tmp/ansible_community.general.github_key_payload_k4s7yu7c/ansible_community.general.github_key_payload.zip/ansible_collections/community/general/plugins/modules/github_key.py\", line 251, in main\n  File \"/tmp/ansible_community.general.github_key_payload_k4s7yu7c/ansible_community.general.github_key_payload.zip/ansible_collections/community/general/plugins/modules/github_key.py\", line 210, in ensure_key_present\n  File \"/tmp/ansible_community.general.github_key_payload_k4s7yu7c/ansible_community.general.github_key_payload.zip/ansible_collections/community/general/plugins/modules/github_key.py\", line 165, in create_key\nAttributeError: module 'datetime' has no attribute 'strftime'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by tomcperry**
##### SUMMARY

Fixes #9185 (broken check mode in the github_key.py module) 

 ##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
github_key

##### ADDITIONAL INFORMATION
It looks as if this is a recent regression caused by #8222 
The change in the previous PR makes sense but it was missing the datetime class 
ie, datetime.strftime(...) instead of datetime.datetime.strftime(...)

### CODE REVIEW

**Comment by tomcperry** [comment]
Apologies, but I am unable to run ansible-test right now as I don't have docker available. 

Changelog fragment on its way

File: changelogs/fragments/9186-fix-broken-check-mode-in-github-key.yml [hunk 1]
```diff
@@ -0,0 +1,2 @@
+bugfixes:
+  - github_key - when check_mode was set, a faulty call to ```datetime.strftime(...)``` was being made which generated an exception. (https://github.com/ansible-collections/community.general/issues/9185)
```
Comment (felixfontein) [inline changelogs/fragments/9186-fix-broken-check-mode-in-github-key.yml:2]:
```suggestion
  - github_key - in check mode, a faulty call to ```datetime.strftime(...)``` was being made which generated an exception (https://github.com/ansible-collections/community.general/issues/9185).
```

**Review by felixfontein — COMMENTED** [review]
Thanks a lot for fixing this! I've one small comment for the changelog, besides that it looks good!

**Comment by felixfontein** [comment]
@tomcperry thanks for fixing this!
@russoz thanks for reviewing!
