### ISSUE TITLE
nsupdate: 'RecordManager' object has no attribute 'keyring' when not using TSIG authentication

### ISSUE THREAD

**Issue by pguinet** [ansible-collections/community.general#11460]
### Summary

The `nsupdate` module fails with `'RecordManager' object has no attribute 'keyring'` when used without TSIG authentication (no `key_name` parameter). This is a regression introduced in version 12.3.0.

### Issue Type

Bug Report

### Component Name

nsupdate

### Ansible Version
```
ansible-core 2.20.1
community.general 12.3.0
```

### Python Version

3.13.11

### Operating System

Debian (Docker container)

### Environment

dnspython 2.6.1

### Steps to Reproduce
```yaml
- name: Remove DNS record without authentication
  community.general.nsupdate:
    record: "test-record"
    type: "CNAME"
    zone: "example.com"
    state: absent
    server: "dns-server.example.com"
  delegate_to: localhost
```

### Expected Results

The module should work without TSIG authentication (as it did in 12.2.0).

### Actual Results
```
fatal: [host -> localhost]: FAILED! => {
    "changed": false,
    "msg": "Task failed: Module failed: 'RecordManager' object has no attribute 'keyring'"
}
```

### Root Cause

In the `RecordManager.__init__` method, `self.keyring` is only initialized when:
1. `key_algorithm` is `gss-tsig` (line 239), OR
2. `key_name` is provided (line 245)

When neither condition is met (no authentication), `self.keyring` is never defined, causing an `AttributeError` later in the code.

**Affected code (plugins/modules/nsupdate.py lines 233-250):**
```python
        if module.params["key_algorithm"] == "hmac-md5":
            self.algorithm = "HMAC-MD5.SIG-ALG.REG.INT"
        elif module.params["key_algorithm"] == "gss-tsig":
            if module.params["key_name"]:
                self.module.fail_json(msg="key_name cannot be used with GSS-TSIG")
            self.algorithm = dns.tsig.GSS_TSIG
            self.keyring, self.keyname = self.init_gssapi()
        else:
            self.algorithm = module.params["key_algorithm"]

        if module.params["key_name"]:
            try:
                self.keyring = dns.tsigkeyring.from_text({module.params["key_name"]: module.params["key_secret"]})
                self.keyname = module.params["key_name"]
            except TypeError:
                module.fail_json(msg="Missing key_secret")
            except binascii_error as e:
                module.fail_json(msg=f"TSIG key error: {e}")
        # BUG: missing else clause to initialize self.keyring = None
```

### Suggested Fix

Add an `else` clause to initialize `self.keyring` and `self.keyname` when no authentication is used:
```python
        if module.params["key_name"]:
            try:
                self.keyring = dns.tsigkeyring.from_text({module.params["key_name"]: module.params["key_secret"]})
                self.keyname = module.params["key_name"]
            except TypeError:
                module.fail_json(msg="Missing key_secret")
            except binascii_error as e:
                module.fail_json(msg=f"TSIG key error: {e}")
        else:
            self.keyring = None
            self.keyname = None
```

### Workaround

Downgrade to community.general 12.2.0:
```bash
ansible-galaxy collection install community.general:==12.2.0 --force
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

### Issue Type

Bug Report

### Component Name

dnsupdate

### Ansible Version

```console (paste below)
$ ansible --version
ansible-core 2.20.1
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 12.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Python:3.13 container
dnspython 2.6.1

### Steps to Reproduce

```yaml
- name: Remove DNS record without authentication
  community.general.nsupdate:
    record: "test-record"
    type: "CNAME"
    zone: "example.com"
    state: absent
    server: "dns-server.example.com"
  delegate_to: localhost
```

### Expected Results

The module should work without TSIG authentication (as it did in 12.2.0).

### Actual Results

```
fatal: [host -> localhost]: FAILED! => {
    "changed": false,
    "msg": "Task failed: Module failed: 'RecordManager' object has no attribute 'keyring'"
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/nsupdate.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/nsupdate.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible-community/collection_bot/blob/main/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @nerzhul
[click here for bot help](https://github.com/ansible-community/collection_bot/blob/main/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
This was introduced in #11425.

CC @Alphix

**Comment by Alphix** [comment]
@pguinet excellent bug report, thanks. I'll have a look at it today or tomorrow unless someone else beats me to it (or feel free to turn this issue into a PR instead since you already have a proposed fix)

**Comment by pguinet** [comment]
@Alphix Done.
Full disclaimer : Both issue and PR have been analyzed and fulfill with the help of Claude Code - Opus 4.5.

**Comment by Alphix** [comment]
> Full disclaimer : Both issue and PR have been analyzed and fulfill with the help of Claude Code - Opus 4.5.

It looked a bit like that to me, mostly because the issue was so detailed :) But in this particular case - no problem...it actually seems reasonable (I haven't tested your code yet, but I have simple testcases ready to go so I'll test the `gss-tsig` and normal key scenarios)

**Comment by Alphix** [comment]
> > Full disclaimer : Both issue and PR have been analyzed and fulfill with the help of Claude Code - Opus 4.5.
> 
> It looked a bit like that to me, mostly because the issue was so detailed :) But in this particular case - no problem...it actually seems reasonable (I haven't tested your code yet, but I have simple testcases ready to go so I'll test the `gss-tsig` and normal key scenarios)

Of course I didn't get around to testing it, and it did break `gss-tsig` support. See https://github.com/ansible-collections/community.general/pull/11712 :)
