### PR TITLE
influxdb_user: Fix bug introduced by PR 2499

### LINKED ISSUE #2609: community.general.influxdb_user error since "Update influxdb_user.py Fixed Multiple No Privileges #2499"
### Summary

Currently have the following task defined to create a DB user:

- name: InfluxDB - Create a telegraf user on localhost with privileges
  community.general.influxdb_user:
    user_name: "{{ telegraf_influxdb_username }}"
    user_password: "{{ telegraf_influxdb_password }}"
    login_username: "{{ influxdb_admin_username }}"
    login_password: "{{ influxdb_admin_password }}"
    grants:
      - database: "{{telegraf_influxdb_database_name}}"
        privilege: 'ALL'

Prior to #2499 this task worked with no issues, now errors with the following:

TASK [docker_tighost : InfluxDB - Create a telegraf user on localhost with privileges] *************
fatal: [bailey]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.15.5 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/psf/.ansible/tmp/ansible-tmp-1621930443.762264-4349-19899814552164/AnsiballZ_influxdb_user.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/psf/.ansible/tmp/ansible-tmp-1621930443.762264-4349-19899814552164/AnsiballZ_influxdb_user.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/psf/.ansible/tmp/ansible-tmp-1621930443.762264-4349-19899814552164/AnsiballZ_influxdb_user.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.influxdb_user', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.influxdb_user', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.general.influxdb_user_payload_ul53ub5s/ansible_community.general.influxdb_user_payload.zip/ansible_collections/community/general/plugins/modules/influxdb_user.py\", line 284, in <module>\r\n  File \"/tmp/ansible_community.general.influxdb_user_payload_ul53ub5s/ansible_community.general.influxdb_user_payload.zip/ansible_collections/community/general/plugins/modules/influxdb_user.py\", line 271, in main\r\n  File \"/tmp/ansible_community.general.influxdb_user_payload_ul53ub5s/ansible_community.general.influxdb_user_payload.zip/ansible_collections/community/general/plugins/modules/influxdb_user.py\", line 177, in set_user_grants\r\nAttributeError: 'list' object has no attribute 'add'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Line 177 reflects s change made in #2499 to the parsing of existing privileges.

### Issue Type

Bug Report

### Component Name

community.general.influxdb_user
influxdb_user.py

### Ansible Version

```console (paste below)
psf@fastnet:ansible % ansible --version                                                     (mainU)
ansible [core 2.11.1] 
  config file = None
  configured module search path = ['/Users/psf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/psf/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.9/bin/ansible
  python version = 3.9.4 (v3.9.4:1f2e3088f3, Apr  4 2021, 12:32:44) [Clang 6.0 (clang-600.0.57)]
  jinja version = 3.0.1
  libyaml = False

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```
Empty

### OS / Environment

MacOS Catalina

### Steps to Reproduce

```yaml (paste below)

- name: InfluxDB - Create a telegraf user on localhost with privileges
  community.general.influxdb_user:
    user_name: "{{ telegraf_influxdb_username }}"
    user_password: "{{ telegraf_influxdb_password }}"
    login_username: "{{ influxdb_admin_username }}"
    login_password: "{{ influxdb_admin_password }}"
    grants:
      - database: "{{telegraf_influxdb_database_name}}"
        privilege: 'ALL'

```

### Expected Results

Expected task to skip user creation if created, or create user if not exist.

### Actual Results

```console (paste below)
TASK [docker_tighost : InfluxDB - Create a telegraf user on localhost with privileges] *************
fatal: [bailey]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.15.5 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/psf/.ansible/tmp/ansible-tmp-1621930443.762264-4349-19899814552164/AnsiballZ_influxdb_user.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/psf/.ansible/tmp/ansible-tmp-1621930443.762264-4349-19899814552164/AnsiballZ_influxdb_user.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/psf/.ansible/tmp/ansible-tmp-1621930443.762264-4349-19899814552164/AnsiballZ_influxdb_user.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.influxdb_user', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.influxdb_user', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.general.influxdb_user_payload_ul53ub5s/ansible_community.general.influxdb_user_payload.zip/ansible_collections/community/general/plugins/modules/influxdb_user.py\", line 284, in <module>\r\n  File \"/tmp/ansible_community.general.influxdb_user_payload_ul53ub5s/ansible_community.general.influxdb_user_payload.zip/ansible_collections/community/general/plugins/modules/influxdb_user.py\", line 271, in main\r\n  File \"/tmp/ansible_community.general.influxdb_user_payload_ul53ub5s/ansible_community.general.influxdb_user_payload.zip/ansible_collections/community/general/plugins/modules/influxdb_user.py\", line 177, in set_user_grants\r\nAttributeError: 'list' object has no attribute 'add'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by sgalea87**
##### SUMMARY
The function to add privileges to a list is incorrect in https://github.com/ansible-collections/community.general/pull/2499.

Fixes #2609

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
influx_db

##### ADDITIONAL INFORMATION
Add an influxdb user

### CODE REVIEW

File: changelogs/fragments/2614-influxdb_user-fix-issue-introduced-in-PR#2499.yml [hunk 1]
```diff
@@ -0,0 +1,2 @@
+bugfixes:
+  - influxdb_user - fix bug introduced in PR #2499. Fixes https://github.com/ansible-collections/community.general/issues/2609 (https://github.com/ansible-collections/community.general/pull/2614).
```
Comment (aminvakil) [inline changelogs/fragments/2614-influxdb_user-fix-issue-introduced-in-PR#2499.yml:2]:
```suggestion
  - influxdb_user - fix bug which removed current privileges instead of appending them to existing ones (https://github.com/ansible-collections/community.general/issues/2609, https://github.com/ansible-collections/community.general/pull/2614).
```

**Review by aminvakil — COMMENTED** [review]
Thanks for opening this PR so quickly!

File: changelogs/fragments/2614-influxdb_user-fix-issue-introduced-in-PR#2499.yml (hunk 1 above)
Comment (sgalea87) [reply changelogs/fragments/2614-influxdb_user-fix-issue-introduced-in-PR#2499.yml]: Fixed, thank you

**Review by felixfontein — APPROVED** [review]

**Review by aminvakil — APPROVED** [review]
LGTM

**Comment by aminvakil** [comment]
Wouldn't hurt to fix typo in title too :)

**Comment by felixfontein** [comment]
@sgalea87 thanks for fixing this!
@aminvakil thanks for reviewing!
