### ISSUE TITLE
keycloak_user_federation: addinfourl instance has no attribute 'getheader'

### ISSUE THREAD

**Issue by kchekam** [ansible-collections/community.general#6172]
### Summary

When I execute my playbook at the level of the creation of an LDAP type "user federation", the task fails with this error message "FAILED! => {"changed": false, "msg": "Could not create component in realm demorealm: addinfourl instance has no attribute 'getheader'"}"
Despite this the "user federation" is well created, and the users imported.

### Issue Type

Bug Report

### Component Name

keycloak_user_federation

### Ansible Version

```
ansible [core 2.11.12] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/debian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/debian/.local/lib/python2.7/site-packages/ansible
  ansible collection location = /home/debian/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/debian/.local/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
  jinja version = 2.11.3
  libyaml = True
```

### Community.general Version

```

# /home/debian/.local/lib/python2.7/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.8.3  

# /home/debian/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.4.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Debian

### Steps to Reproduce

```
---
- name: Create LDAP user federation
  community.general.keycloak_user_federation:
    auth_keycloak_url: https://keycloak.dev.onesi.ca/auth
    auth_realm: master
    auth_username: admin
    auth_password: password
    realm: demorealm
    name: ldap
    state: present
    provider_id: ldap
    provider_type: org.keycloak.storage.UserStorageProvider
    config:
      priority: 0
      enabled: true
      cachePolicy: NO_CACHE
      batchSizeForSync: 1000
      editMode: READ_ONLY
      importEnabled: true
      syncRegistrations: false
      vendor: other
      usernameLDAPAttribute: uid
      rdnLDAPAttribute: uid
      uuidLDAPAttribute: entryUUID
      userObjectClasses: inetOrgPerson, organizationalPerson
      connectionUrl: ldap://uri
      usersDn: userdn
      authType: simple
      bindDn: bindn
      bindCredential: password
      searchScope: 1
      validatePasswordPolicy: false
      trustEmail: false
      useTruststoreSpi: ldapsOnly
      connectionPooling: true
      pagination: true
      allowKerberosAuthentication: false
      debug: false
      useKerberosForPasswordAuthentication: false
    mappers:
      - name: "full name"
        providerId: "full-name-ldap-mapper"
        providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
        config:
          ldap.full.name.attribute: cn
          read.only: true
          write.only: false
```

### Expected Results

No failed task

### Actual Results

```

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not create component in realm demorealm: addinfourl instance has no attribute 'getheader'"

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/keycloak_user_federation.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/keycloak_user_federation.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @eikef @laurpaum @ndclt
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
`KeycloakAPI.create_component()` in the module utils (plugins/module_utils/identity/keycloak/keycloak.py) calls `resp.getheader('Location')`. I'm wondering whether this is just something that doesn't work on ansible-core 2.11 (or other older ansible-core versions), or whether this is broken in general. In any case, please note that ansible-core 2.11 is End of Life, so upgrading to a newer version is a good idea anyway :) (If it then works, this is still a bug that should be fixed.)

**Comment by ansibullbot** [comment]
cc @mattock
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @thomasbach-dev
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Please note that all Keycloak content from this collection is being moved to the [`middleware_automation.keycloak`](https://galaxy.ansible.com/ui/repo/published/middleware_automation/keycloak/) collection, maintained in the [github.com/ansible-middleware/keycloak repository](https://github.com/ansible-middleware/keycloak). Please check out the [thread in the Ansible forum](https://forum.ansible.com/t/41746) for more information. The current modules in community.general will eventually be deprecated and replaced with redirects to their equivalents in `middleware_automation.keycloak`.
