### ISSUE TITLE
plugins.callback.unixy: Warning 'CallbackModule' object has no attribute 'display_failed_stderr'

### ISSUE THREAD

**Issue by kerel-fs** [ansible-collections/community.general#5600]
### Summary

When using the `community.general.unixy` callback plugin with a recent version of ansible I get a warning `'CallbackModule' object has no attribute 'display_failed_stderr'` and the task output is not shown.

This is a regression introduced by https://github.com/ansible/ansible/commit/dbdbfe845adac977a78c6484da1c5923754d83a2 via https://github.com/ansible/ansible/pull/77677

I already prepared a patch to fix this by using the new `self.get_option` interface and I'd be happy to open a PR with it.

### Issue Type

Bug Report

### Component Name

community.general.unixy

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kerel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/kerel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.0  
```

### Configuration

```console (paste below)
$ cat ansible.cfg
[defaults]
stdout_callback = unixy
```

### OS / Environment

Manjaro Linux 22.0

### Steps to Reproduce

Any playbook with tasks producing output will trigger this. I tested with the following:

`playbook.yml`: 
```yaml (paste below)
---
- hosts: all
  tasks:
    - ansible.builtin.ping:
```

```
$ ansible-playbook playbook.yml

# in my specific case I run inside a virtualbox using vagrant:
$ sudo vagrant provision debian_bullseye --provision-with version
```

### Expected Results

The task output should be shown.

### Actual Results

Task output is missing, but warning shown:
```console (paste below)
==> debian_bullseye: Running provisioner: version (ansible)...
    debian_bullseye: Running ansible-playbook...
Executing playbook check_version.yml

- all on hosts: all -
Gathering Facts...
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible_collections.community.general.plugins.callback.unixy.CallbackModule
object at 0x7fb06d861a20>): 'CallbackModule' object has no attribute
'display_failed_stderr'
ansible.builtin.ping...

- Play recap -
  debian_bullseye            : ok=2    changed=0    unreachable=0    failed=0    rescued=0    ignored=0   
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/callback/unixy.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/callback/unixy.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @akatch
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by kerel-fs** [comment]
!component =plugins/callback/unixy.py
