### ISSUE TITLE
AttributeError: 'LookupModule' object has no attribute '_load_name' in dig.run()

### ISSUE THREAD

**Issue by loop-evgeny** [ansible-collections/community.general#5743]
### Summary

When I try to call run() on the dig LookupModule in Python code (in a custom plugin) it fails with the error in the title.

### Issue Type

Bug Report

### Component Name

plugins/lookup/dig.py

### Ansible Version

```
$ ansible --version
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/home/em/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/em/venv-ansible-2.14/lib/python3.9/site-packages/ansible
  ansible collection location = /home/em/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/em/venv-ansible-2.14/bin/ansible
  python version = 3.9.5 (default, Nov 23 2021, 15:27:38) [GCC 9.3.0] (/home/em/venv-ansible-2.14/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```
$ ansible-galaxy collection list community.general
# /home/em/venv-ansible-2.14/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.1.0  
```

### Configuration

```
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

Linux Mint 20

### Steps to Reproduce

Run the following Python code:

```
from ansible_collections.community.general.plugins.lookup.dig import LookupModule

dig_module = LookupModule()
print("Running dig module")
result = dig_module.run(['example.org'])
print(f"It worked: {result}")
```

### Expected Results

With community.general 5.8.3, ansible-core 2.13.7 it succeeds:

```
$ python test_dig_run.py
Running dig module
It worked: ['93.184.216.34']
```

### Actual Results

With community.general 6.1.0, ansible-core 2.14.1 it raises an exception:

```
$ python test_dig_run.py 
Running dig module
Traceback (most recent call last):
  File "/media/sf_work/lops2/ansible/tests/test_dig_run.py", line 5, in <module>
    result = dig_module.run(['example.org'])
  File "/home/em/venv-ansible-2.14/lib/python3.9/site-packages/ansible_collections/community/general/plugins/lookup/dig.py", line 294, in run
    self.set_options(var_options=variables, direct=kwargs)
  File "/home/em/venv-ansible-2.14/lib/python3.9/site-packages/ansible/plugins/__init__.py", line 98, in set_options
    self._options = C.config.get_plugin_options(self.plugin_type, self._load_name, keys=task_keys, variables=var_options, direct=direct)
AttributeError: 'LookupModule' object has no attribute '_load_name'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/lookup/dig.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/lookup/dig.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jpmens
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Why do you expect this to work? I don't see any documentation saying that you can use Ansible modules and plugins as regular Python modules.

**Comment by felixfontein** [comment]
needs_info

**Comment by loop-evgeny** [comment]
I don't remember how that code originally came about, but it has worked in Ansible 2.9-2.13, and we rely on it in our own plugin that wraps the dig plugin. (We do this to work around https://github.com/ansible/ansible/issues/41192 which, it seems, will never be fixed despite there being a PR that fixes it.) So we cannot upgrade beyond Ansible 2.13 if we cannot get around this somehow.

**Comment by felixfontein** [comment]
@loop-evgeny you have to use Ansible's lookup plugin loader to properly load and run a plugin. You cannot just expect random code to work. I suggest you look into how ansible-core loads and processes plugins first.

**Comment by felixfontein** [comment]
Also you should look at the `fail_on_error` option of the plugin (https://github.com/ansible-collections/community.general/blob/main/plugins/lookup/dig.py#L50).

**Comment by loop-evgeny** [comment]
Thanks @felixfontein, I did not realise `fail_on_error` was added! So it seems that the old NXDOMAIN issue was fixed after all. We have a couple of other workarounds in our custom plugin as well, though, so would ideally keep using that. Could you suggest where to look for the plugin loading code? ansible-core is a big code base!

**Comment by felixfontein** [comment]
I would try `from ansible.plugins.loader import lookup_loader` and then `lookup_loader.get("community.general.dig")` to get hold of a plugin instance. The lookup plugin unit tests also use that.

**Comment by felixfontein** [comment]
Closing since this is not a bug in the collection.

**Comment by loop-evgeny** [comment]
>`from ansible.plugins.loader import lookup_loader` and then `lookup_loader.get("community.general.dig")` to get hold of a plugin instance

That seems to work on both 2.13 and 2.14 - thank you!
