### ISSUE TITLE
lxc: container_command does not seem to be executed anymore

### ISSUE THREAD

**Issue by na-ate** [ansible-collections/community.general#11360]
### Summary

I was using lxc_container on my deb12 laptop and container_command was executed correctly.
Now that I switched to deb13, container_command does not seem to be executed anymore.
I think the collection got updated in the debian package and it is not working anymore

I am running collections 10.7.0, tried also with 12.2.0 but no luck.

### Issue Type

Bug Report

### Component Name

The issue is about lxc_container module of community.general.

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.19.0b6]
  config file = /root/git/ansible-laptop/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```


### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.7.0 
```
I tried also with 12.2.0 but it did not improve things.

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/root/git/ansible-laptop/ansible.cfg) = ['/usr/share/ansible/collections']
CONFIG_FILE() = /root/git/ansible-laptop/ansible.cfg
DEFAULT_JINJA2_EXTENSIONS(/root/git/ansible-laptop/ansible.cfg) = ['jinja2.ext.do', 'jinja2.ext.i18n']
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less

GALAXY_SERVERS:
```


### OS / Environment

Debian 13.1

### Steps to Reproduce

Create a container with ansible
```yaml
- name: Create container
  community.general.lxc_container:
    name: backup-restorer
    template: debian
    template_options: "-r trixie -a amd64"
    backing_store: lvm
    vg_name: '{{ vg_name }}'
    fs_size: 16G
    state: started
    container_config:
      - "lxc.net.0.type=veth"
      - "lxc.net.0.link=guests0"
      - "lxc.net.0.flags=up"
      - "lxc.net.0.ipv4.address=172.16.2.1/24"
      - "lxc.net.0.ipv4.gateway=172.16.2.254"
    container_command: |
      touch /root/if-you-see-me-it-means-container_command_is_working_again
      apt update
      apt remove -y --purge isc-dhcp-client
      apt install -y openssh-server python3 python3-apt
      mkdir -p /root/.ssh
      chmod 700 /root/.ssh
      echo '{{ guests_ssh_key }}' > /root/.ssh/authorized_keys
      chmod 400 /root/.ssh/authorized_keys
```
```bash
[11:52:44] root@framework:~/git/ansible-laptop(master⚡) # ansible-playbook -i inventory backup-restorer.yml --ask-vault-pass -D                                                                                                                                                                                                                                                          [...]
Everything went well
```

### Expected Results

I should have at least:
- the file /root/if-you-see-me-it-means-container_command_is_working_again in the container
- the file /root/.ssh/authorized_keys in the container
- the file /tmp/lxc-attach-script-log in the container
- the file /tmp/lxc-attach-script-err in the container
- ....
But I have none of them.

### Actual Results

Then we can see inside the container that we have nothing:
```bash
[11:50:32] root@framework:~/git/ansible-laptop(master⚡) # lxc-attach -n backup-restorer                                        
root@backup-restorer:/# ls -la /root
total 20
drwx------  3 root root 4096 31 déc.  11:50 .
drwxr-xr-x 19 root root 4096 31 déc.  11:50 ..
-rw-r--r--  1 root root  607  7 nov.  18:40 .bashrc
-rw-r--r--  1 root root  132 31 déc.  11:50 .profile
drwx------  2 root root 4096 30 déc.  19:40 .ssh
root@backup-restorer:/# ls -la /root/.ssh/
total 8
drwx------ 2 root root 4096 30 déc.  19:40 .
drwx------ 3 root root 4096 31 déc.  11:50 ..
root@backup-restorer:/# ls -la /tmp/
total 4
drwxrwxrwt  6 root root  120 31 déc.  11:50 .
drwxr-xr-x 19 root root 4096 31 déc.  11:50 ..
drwxrwxrwt  2 root root   40 31 déc.  11:50 .font-unix
drwxrwxrwt  2 root root   40 31 déc.  11:50 .ICE-unix
drwxrwxrwt  2 root root   40 31 déc.  11:50 .X11-unix
drwxrwxrwt  2 root root   40 31 déc.  11:50 .XIM-unix
```


### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/lxc_container.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/lxc_container.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible-community/collection_bot/blob/main/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @cloudnull
[click here for bot help](https://github.com/ansible-community/collection_bot/blob/main/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
CC @russoz, though this is likely not related to #11204 (which appeared in 12.2.0).

**Comment by russoz** [comment]
@na-ate no errors in either case?

In the deb12, what were the versions for Python, Ansible, LXC, and the lxc python package? (Hoping you still have the deb12 to test on)

Also, could you please provide the LXC and lxc python package versions for the new setup?

**Comment by na-ate** [comment]
I have a deb12 VM on my laptop and I was able to make container_command work on it.
So here is the setup of my deb12 VM where it works
```bash
# Still the same task 
root@dockerer:~# cat backup-restorer/roles/backup-restorer/tasks/main.yaml 
---
- name: Create container
  community.general.lxc_container:
    name: backup-restorer
    template: debian
    template_options: "-r trixie -a amd64"
    backing_store: lvm
    vg_name: 'vg-data'
    fs_size: 16G
    state: started
    container_config:
      - "lxc.net.0.type=veth"
      - "lxc.net.0.link=lxcbr0"
      - "lxc.net.0.flags=up"
      - "lxc.net.0.ipv4.address=10.0.3.10/24"
      - "lxc.net.0.ipv4.gateway=10.0.3.1"
    container_command: |
      touch /root/if-you-see-me-it-means-container_command_is_working_again
      apt update
      apt remove -y --purge isc-dhcp-client
      apt install -y openssh-server python3 python3-apt
      mkdir -p /root/.ssh
      chmod 700 /root/.ssh
      echo '{{ guests_ssh_key }}' > /root/.ssh/authorized_keys
      chmod 400 /root/.ssh/authorized_keys
      mkdir -p /usr/local/scripts
root@dockerer:~# cat /etc/debian_version 
12.9
root@dockerer:~# ansible --version
ansible [core 2.14.18]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
root@dockerer:~# apt-cache policy lxc
lxc:
  Installed : 1:5.0.2-1+deb12u3+b1
  Candidate : 1:5.0.2-1+deb12u3+b1
root@dockerer:~# python3 --version
Python 3.11.2
root@dockerer:~# apt-cache policy python3-lxc
python3-lxc:
  Installed : 1:5.0.0-1+b1
  Candidate : 1:5.0.0-1+b1
root@dockerer:~# ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2 

# Now I see it is ok
root@dockerer:~# lxc-attach -n backup-restorer
root@backup-restorer:~# ls /root/
if-you-see-me-it-means-container_command_is_working_again
root@backup-restorer:~# ls /root/.ssh/
authorized_keys
```

On my deb13 laptop where it does not work
```bash
[18:18:37] root@framework:~ # cat /etc/debian_version 
13.1
[18:18:06] root@framework:~ # ansible --version
ansible [core 2.19.0b6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
[18:07:06] root@framework:~ » apt-cache policy lxc    
lxc:
  Installed : 1:6.0.4-4+b3
  Candidate : 1:6.0.4-4+b3
[18:12:20] root@framework:~ » python3 --version
Python 3.13.5
[18:07:09] root@framework:~ » apt-cache policy python3-lxc
python3-lxc:
  Installed:: 1:5.0.0-2+b3
  Candidate : 1:5.0.0-2+b3

[18:18:09] root@framework:~ # ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.7.0 
```

I hope I provided all the info you requested.

And yes, no errors in either case. It is as if the code path for _execute_command was not hit on deb13.

**Comment by russoz** [comment]
@na-ate I think that will definitely help. I am not the maintainer of that module, but I must confess I am curious about it - especially because it worked in c.g. 6.6.2 (!! Jun 2023), but it did not in 10.7.0 (May 2025). In the unlikely case I have spare time, I may try and play a bit with this.

**Comment by russoz** [comment]
Though I must say there is not a lot of difference in the module's code between those versions. Other than doc changes, it is literally changing a `dict((x,y) for ...)` with an actual dict -comprehension `{x: y for ...}`, and fixing a typo in a variable name (that appears not to be used anyways).

**Comment by na-ate** [comment]
I've installed community.general 12.2.0 on my deb12 VM and it does not work anymore
```bash
root@dockerer:~/backup-restorer# ansible-galaxy collection list community.general

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 12.2.0 

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2 
root@dockerer:~/backup-restorer# ansible-playbook -i inventory playbook.yaml -D -vvv
ansible-playbook [core 2.14.18]
  config file = /root/backup-restorer/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /root/backup-restorer/ansible.cfg as config file
host_list declined parsing /root/backup-restorer/inventory/hosts as it did not pass its verify_file() method
script declined parsing /root/backup-restorer/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /root/backup-restorer/inventory/hosts as it did not pass its verify_file() method
Parsed /root/backup-restorer/inventory/hosts inventory source with ini plugin
[WARNING]: Collection community.general does not support Ansible version 2.14.18
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: playbook.yaml ****************************************************************************************************************************************************************************************************************************************
1 plays in playbook.yaml

PLAY [all] *****************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************
task path: /root/backup-restorer/playbook.yaml:2
<dockerer> ESTABLISH LOCAL CONNECTION FOR USER: root
<dockerer> EXEC /bin/sh -c 'echo ~root && sleep 0'
<dockerer> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1767435695.4477148-1771-157907285495350 `" && echo ansible-tmp-1767435695.4477148-1771-157907285495350="` echo /root/.ansible/tmp/ansible-tmp-1767435695.4477148-1771-157907285495350 `" ) && sleep 0'
<dockerer> Attempting python interpreter discovery
<dockerer> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<dockerer> EXEC /bin/sh -c '/usr/bin/python3.11 && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/setup.py
<dockerer> PUT /root/.ansible/tmp/ansible-local-1767k8fe0nx9/tmpdh5a4xxp TO /root/.ansible/tmp/ansible-tmp-1767435695.4477148-1771-157907285495350/AnsiballZ_setup.py
<dockerer> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1767435695.4477148-1771-157907285495350/ /root/.ansible/tmp/ansible-tmp-1767435695.4477148-1771-157907285495350/AnsiballZ_setup.py && sleep 0'
<dockerer> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1767435695.4477148-1771-157907285495350/AnsiballZ_setup.py && sleep 0'
<dockerer> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1767435695.4477148-1771-157907285495350/ > /dev/null 2>&1 && sleep 0'
ok: [dockerer]

TASK [backup-restorer : Create container] **********************************************************************************************************************************************************************************************************************
task path: /root/backup-restorer/roles/backup-restorer/tasks/main.yaml:2
<dockerer> ESTABLISH LOCAL CONNECTION FOR USER: root
<dockerer> EXEC /bin/sh -c 'echo ~root && sleep 0'
<dockerer> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1767435696.5321178-1882-163969468994483 `" && echo ansible-tmp-1767435696.5321178-1882-163969468994483="` echo /root/.ansible/tmp/ansible-tmp-1767435696.5321178-1882-163969468994483 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/community/general/plugins/modules/lxc_container.py
<dockerer> PUT /root/.ansible/tmp/ansible-local-1767k8fe0nx9/tmplgtxotr2 TO /root/.ansible/tmp/ansible-tmp-1767435696.5321178-1882-163969468994483/AnsiballZ_lxc_container.py
<dockerer> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1767435696.5321178-1882-163969468994483/ /root/.ansible/tmp/ansible-tmp-1767435696.5321178-1882-163969468994483/AnsiballZ_lxc_container.py && sleep 0'
<dockerer> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1767435696.5321178-1882-163969468994483/AnsiballZ_lxc_container.py && sleep 0'
<dockerer> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1767435696.5321178-1882-163969468994483/ > /dev/null 2>&1 && sleep 0'
changed: [dockerer] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "archive": false,
            "archive_compression": "gzip",
            "archive_path": null,
            "backing_store": "lvm",
            "clone_name": null,
            "clone_snapshot": false,
            "config": null,
            "container_command": "touch /root/if-you-see-me-it-means-container_command_is_working_again\napt update\napt remove -y --purge isc-dhcp-client\napt install -y openssh-server python3 python3-apt\nmkdir -p /root/.ssh\nchmod 700 /root/.ssh\necho 'ssh-rsa xxx' > /root/.ssh/authorized_keys\nchmod 400 /root/.ssh/authorized_keys\nmkdir -p /usr/local/scripts\n",
            "container_config": [
                "lxc.net.0.type=veth",
                "lxc.net.0.link=lxcbr0",
                "lxc.net.0.flags=up",
                "lxc.net.0.ipv4.address=10.0.3.10/24",
                "lxc.net.0.ipv4.gateway=10.0.3.1"
            ],
            "container_log": false,
            "container_log_level": "INFO",
            "directory": null,
            "fs_size": "16G",
            "fs_type": "ext4",
            "lv_name": "backup-restorer",
            "lxc_path": null,
            "name": "backup-restorer",
            "state": "started",
            "template": "debian",
            "template_options": "-r trixie -a amd64",
            "thinpool": null,
            "vg_name": "vg-data",
            "zfs_root": null
        }
    },
    "lxc_container": {
        "init_pid": 2307,
        "interfaces": [
            "eth0",
            "lo"
        ],
        "ips": [
            "10.0.3.10"
        ],
        "name": "backup-restorer",
        "state": "running"
    }
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************
dockerer                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
root@dockerer:~# lxc-attach -n backup-restorer
root@backup-restorer:~# ls /root/
root@backup-restorer:~# 
```

But surely normal with the message "[WARNING]: Collection community.general does not support Ansible version 2.14.18"

**Comment by na-ate** [comment]
Small correction: i was not using the correct package of ansible in d13:
```bash
root@framework:~/git/ansible-laptop(master○) # apt-cache policy ansible       
ansible:
  Installed : 12.0.0~a6+dfsg-1
  Candidate : 12.0.0~b5+dfsg-0+deb13u1
 Table de version :
     12.0.0~b5+dfsg-0+deb13u1 500
        500 http://ftp.debian.org/debian trixie/main amd64 Packages
        500 http://ftp.debian.org/debian trixie/main i386 Packages
 *** 12.0.0~a6+dfsg-1 100
        100 /var/lib/dpkg/status
root@framework:~/git/ansible-laptop(master○) # apt-cache policy ansible       
ansible:
  Installed : 12.0.0~b5+dfsg-0+deb13u1
  Candidate : 12.0.0~b5+dfsg-0+deb13u1
root@framework:~/git/ansible-laptop(master○) # ansible-galaxy collection list community.general            
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_JINJA2_EXTENSIONS option. Reason: Jinja2 extensions have been deprecated
Alternatives: Ansible-supported Jinja plugins (tests, filters, lookups). This feature will be removed from ansible-core version 2.23.


# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 11.2.1 #got upgrade from 10.7.0 to 11.2.1
```
Issue remain the same on d13 though:
- 11.2.1-> ko
- 12.2.0 -> ko

I installed incrementing versions of community.general on my deb12 VM and found the following:
- 7.0.0 -> ok
- 8.0.0 -> ok
- 9.0.0 -> ok
- 10.0.0 -> ok
- 10.7.0 -> ok
- 11.2.1 -> ok
- 12.0.0 -> ok
- 12.1.0 -> ok
- 12.2.0 -> ko (but [WARNING]: Collection community.general does not support Ansible version 2.14.18)



So it seems it would not be community.general the culprit but ansible ?
Any big change between ansible 2.14.18 (deb12 where it works) and ansible 2.19.0b6 (deb13 where it does not work) ?

**Comment by na-ate** [comment]
On my deb13 laptop where it does not work, I installed ansible from pip, still no luck
```bash
[12:10:26] root@framework:~/git/ansible-laptop(master⚡) # ansible --version
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_JINJA2_EXTENSIONS option. Reason: Jinja2 extensions have been deprecated
Alternatives: Ansible-supported Jinja plugins (tests, filters, lookups). This feature will be removed from ansible-core version 2.23.

ansible [core 2.20.1]
  config file = /root/git/ansible-laptop/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.13/dist-packages/ansible
  ansible collection location = /root/.ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
[12:10:29] root@framework:~/git/ansible-laptop(master⚡) # ansible-galaxy collection list community.general
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_JINJA2_EXTENSIONS option. Reason: Jinja2 extensions have been deprecated
Alternatives: Ansible-supported Jinja plugins (tests, filters, lookups). This feature will be removed from ansible-core version 2.23.


# /usr/local/lib/python3.13/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 12.2.0 

```

container_command is still not working

**Comment by na-ate** [comment]
On the deb12 VM, using ansible from pip, it still works
```
root@dockerer:~/backup-restorer# /usr/local/bin/ansible --version
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_JINJA2_EXTENSIONS option. Reason: Jinja2 extensions have been deprecated
Alternatives: Ansible-supported Jinja plugins (tests, filters, lookups). This feature will be removed from ansible-core version 2.23.

ansible [core 2.19.5]
  config file = /root/backup-restorer/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/dist-packages/ansible
  ansible collection location = /root/.ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  pyyaml version = 6.0 (with libyaml v0.2.5)
root@dockerer:~/backup-restorer# /usr/local/bin/ansible-galaxy collection list community.general
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_JINJA2_EXTENSIONS option. Reason: Jinja2 extensions have been deprecated
Alternatives: Ansible-supported Jinja plugins (tests, filters, lookups). This feature will be removed from ansible-core version 2.23.


# /usr/local/lib/python3.11/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 11.4.2 
```

I am not sure what to conclude from all this testing 😆

**Comment by na-ate** [comment]
Just in case there was something wrong with my laptop, I spun a vanilla deb13 VM and ran my playbook, still the same issue
```bash
root@debian13-vanilla:~/backup-restorer# cat /etc/debian_version 
13.2
root@debian13-vanilla:~/backup-restorer# ansible --version
ansible [core 2.19.4]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
root@debian13-vanilla:~/backup-restorer# ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 11.2.1 
root@debian13-vanilla:~/backup-restorer# apt-cache policy lxc
lxc:
  Installed : 1:6.0.4-4+b3
  Candidate : 1:6.0.4-4+b3
 Version table :
 *** 1:6.0.4-4+b3 500
        500 http://deb.debian.org/debian trixie/main amd64 Packages
        100 /var/lib/dpkg/status
root@debian13-vanilla:~/backup-restorer# apt-cache policy python3-lxc
python3-lxc:
  Installed : 1:5.0.0-2+b3
  Candidate : 1:5.0.0-2+b3
Version table :
 *** 1:5.0.0-2+b3 500
        500 http://deb.debian.org/debian trixie/main amd64 Packages
        100 /var/lib/dpkg/status
root@debian13-vanilla:~/backup-restorer# lxc-attach -n backup-restorer
root@backup-restorer:/# ls /root/
root@backup-restorer:/# 
```

So, on a vanilla deb13, we have still the same issue

**Comment by dawagner** [comment]
I've had the same issue and traced it to this known issue: https://github.com/lxc/python3-lxc/issues/35. The bug is fixed in the python module but there was no new release since then, so I reported that to debian too: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1135733

I worked around it for now by manually installing the fixed version like so:

```shell
apt install build-essential pkg-config python3-dev lxc-dev
pip install  --break-system-packages git+https://github.com/lxc/python3-lxc@018c4ed482cfccbb89e39fe0dbaad9fe98ee5dd4a
```

YMMV. You don't even need to uninstall the python3-lxc deb package: the one installed by pip has priority.

**Comment by usbpc** [comment]
> YMMV. You don't even need to uninstall the python3-lxc deb package: the one installed by pip has priority.

I can't replicate your fix.

While trying to further analyze #11490 I found this issue. I tried to test out manually installing specific version of python3-lxc into a venv that my ansible uses with these tasks:

```
- name: Install system packages required for python3-lxc
  ansible.builtin.apt:
    name:
      - build-essential
      - pkg-config
      - python3-dev
      - lxc-dev
    state: present

- name: Create python venv for ansible
  ansible.builtin.pip:
    name:
      - git+https://github.com/lxc/python3-lxc@018c4ed482cfccbb89e39fe0dbaad9fe98ee5dd4
    virtualenv: /opt/ansible/venv
    virtualenv_command: python3 -m venv
```

And pointing ansible to use this venv with `ansible_python_interpreter: /opt/ansible/venv/bin/python` in my inventory.

However neither `container_command` nor `container_config` work for me.

Interestingly I noticed a Error that only shows up with debug logs:

```
(0, b'\r\n\x1b[1;35mTypeError\x1b[0m: \x1b[35mcreate_script() missing 1 required positional argument: \'module\'\x1b[0m\r\n\r\n{"changed": true, "lxc_container": {"interfaces": ["eth0", "lo"], "ips": ["10.102.101.2", "2 001:41d0:f00:2d04::2"], "state": "running", "init_pid": 3506504, "name": "forgejo-runner"}, "invocation": {"module_args": {"container_command": "touch /root/standalone-command-test\\n", "name": "forgejo-runner", "state": "started", "tem plate": "ubuntu", "backing_store": "dir", "vg_name": "lxc", "fs_type": "ext4", "fs_size": "5G", "container_log": false, "container_log_level": "INFO", "clone_snapshot": false, "archive": false, "archive_compression": "gzip", "template_o ptions": null, "config": null, "thinpool": null, "directory": null, "zfs_root": null, "lv_name": "forgejo-runner", "lxc_path": null, "container_config": null, "clone_name": null, "archive_path": null}}}\r\n', b'Shared connection to 217. 182.199.35 closed.\r\n')
```

**Comment by dawagner** [comment]
If you're on trixie, you should now be able to get container_command working without any hack: the fix has been cherry-picked by debian and the new package version is now available in the repositories.

**Comment by usbpc** [comment]
@dawagner I feel like something in my setup must be weird. Because to get it working with version 13.0.0 of the community.general collection I had to do some modifications to the package source.

The installed version of python3-lxc is `1:5.0.0-2+deb13u1`, so that should be the fixed version. But after installing that I still got the `TypeError` in the `-vvvv` logs as noted in my last comment.

I had to remove the (as far as I can tell unused) module parameter here
https://github.com/ansible-collections/community.general/blob/cbc6f6eed3dd6725f9618a8b9682616dc9dd7c3d/plugins/modules/lxc_container.py#L816
and
https://github.com/ansible-collections/community.general/blob/cbc6f6eed3dd6725f9618a8b9682616dc9dd7c3d/plugins/module_utils/_lxc.py#L36

with that modification the container_command now works.

**Comment by usbpc** [comment]
@russoz [I think you added the create_script function.](https://github.com/ansible-collections/community.general/pull/11204#issuecomment-3572513341)

Why does it have the unused module parameter?

From my testing it seems only a single parameter gets passed to the function given to attach_wait, without any unpacking of the given list/tuple:
```
>>> def print_hostname(first):
...     with open("/etc/hostname") as fd:
...         print(f"Hostname: {fd.read().strip()} test: {first}")
... 
>>> c.attach_wait(print_hostname, ("testing", "blub"))
Hostname: forgejo-runner test: ('testing', 'blub')
-1
>>> c.attach_wait(print_hostname, ["testing", "blub"], "meh")
Traceback (most recent call last):
  File "<python-input-27>", line 1, in <module>
    c.attach_wait(print_hostname, ["testing", "blub"], "meh")
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: function takes at most 2 arguments (3 given)
>>> c.attach_wait(print_hostname, ["testing", "blub"])
Hostname: forgejo-runner test: ['testing', 'blub']
-1
```

**Comment by russoz** [comment]
It was a while ago, I will have spend more time with this one.
