### PR TITLE
unixy Callback: Fix typo using ansibles config manager

### LINKED ISSUE #5600: plugins.callback.unixy: Warning 'CallbackModule' object has no attribute 'display_failed_stderr'
### Summary

When using the `community.general.unixy` callback plugin with a recent version of ansible I get a warning `'CallbackModule' object has no attribute 'display_failed_stderr'` and the task output is not shown.

This is a regression introduced by https://github.com/ansible/ansible/commit/dbdbfe845adac977a78c6484da1c5923754d83a2 via https://github.com/ansible/ansible/pull/77677

I already prepared a patch to fix this by using the new `self.get_option` interface and I'd be happy to open a PR with it.

### Issue Type

Bug Report

### Component Name

community.general.unixy

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kerel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/kerel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.0  
```

### Configuration

```console (paste below)
$ cat ansible.cfg
[defaults]
stdout_callback = unixy
```

### OS / Environment

Manjaro Linux 22.0

### Steps to Reproduce

Any playbook with tasks producing output will trigger this. I tested with the following:

`playbook.yml`: 
```yaml (paste below)
---
- hosts: all
  tasks:
    - ansible.builtin.ping:
```

```
$ ansible-playbook playbook.yml

# in my specific case I run inside a virtualbox using vagrant:
$ sudo vagrant provision debian_bullseye --provision-with version
```

### Expected Results

The task output should be shown.

### Actual Results

Task output is missing, but warning shown:
```console (paste below)
==> debian_bullseye: Running provisioner: version (ansible)...
    debian_bullseye: Running ansible-playbook...
Executing playbook check_version.yml

- all on hosts: all -
Gathering Facts...
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible_collections.community.general.plugins.callback.unixy.CallbackModule
object at 0x7fb06d861a20>): 'CallbackModule' object has no attribute
'display_failed_stderr'
ansible.builtin.ping...

- Play recap -
  debian_bullseye            : ok=2    changed=0    unreachable=0    failed=0    rescued=0    ignored=0   
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by kerel-fs**
##### SUMMARY
Fixes typo introduced in 53da86c, thus

Fixes #5600 (again).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`unixy`

##### ADDITIONAL INFORMATION

In https://github.com/ansible-collections/community.general/pull/5601#discussion_r1058867612 it was realized that the patch contained a typo.  This gets corrected with this PR.

Does it require another changelog fragment, or is it sufficient to have [changelogs/fragments/5601-unixy-callback-use-config-manager.yml](https://github.com/ansible-collections/community.general/blob/main/changelogs/fragments/5601-unixy-callback-use-config-manager.yml) ?

### CODE REVIEW

**Comment by felixfontein** [comment]
> Does it require another changelog fragment, or is it sufficient to have [changelogs/fragments/5601-unixy-callback-use-config-manager.yml](https://github.com/ansible-collections/community.general/blob/main/changelogs/fragments/5601-unixy-callback-use-config-manager.yml) ?

It needs a new one, since that fragment is already parts of releases (in the backports).

**Comment by kerel-fs** [comment]
ok! Changelog Fragment added & force-pushed.
Sorry, I'm not sure at which point my contribution makes more work than it solved problems.
Feel free to amend the patch yourself / let me know what to change if patch is insufficient.

My personal learning: Test my own PRs even for (seemingly) trivial drive-by contributions.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
> ok! Changelog Fragment added & force-pushed.

Thanks!

> Sorry, I'm not sure at which point my contribution makes more work than it solved problems.

I don't think it did so far. You fixed a bug, and while introducing a new one, that one was very easy to fix. (I would have done it myself if nobody would have created a PR in a few days :) )

> My personal learning: Test my own PRs even for (seemingly) trivial drive-by contributions.

That's always a good idea ;-)

In an optimal world, we would have (extensive enough) tests for this plugin so that the typo would have been noticed - or probably we would have noticed that the plugin is broken long before you submitted your first PR. Unfortunately many plugins/modules in this collection do not have tests (we enforce tests for new ones, so at least in the future it will be better...), so things break from time to time without anyone noticing until someone actually tries to use it...

**Comment by felixfontein** [comment]
@kerel-fs thanks for fixing this!
